name: Pull Request workflow 1

on:
  - pull_request

jobs:
  Cloudformation-linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Cloud Formation Linter with Latest Version
        uses: scottbrenner/cfn-lint-action@v2
        with:
          command:  cfn-lint -t ./vpc-basic-iac/vpc-template.yaml
          
